apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aegisgraph-sentinel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegisgraph-sentinel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "aegisgraph-sentinel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aegisgraph-sentinel.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "aegisgraph-sentinel.fullname" . }}-config
          env:
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aegisgraph-sentinel.fullname" . }}-secret
                  key: NEO4J_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "aegisgraph-sentinel.fullname" . }}-secret
                  key: JWT_SECRET
            - name: AEGIS_API_KEY_HASHES
              valueFrom:
                secretKeyRef:
                  name: {{ include "aegisgraph-sentinel.fullname" . }}-secret
                  key: AEGIS_API_KEY_HASHES
          startupProbe:
            httpGet:
              path: /api/v1/health/startup
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
