best_epoch: 0
best_val_f1: 0.0
test_metrics:
  accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  epoch: 6
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.1644103080034256
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 0
  tp: 0
train_metrics:
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    27Zt27Ztyz8=
  epoch: 0
  f1: 0.26666666666666666
  fn: 1
  fp: 10
  fraud_f1: 0.8
  fraud_precision: 1.0
  fraud_recall: 0.6666666666666666
  loss: 0.12078821286559105
  pr_auc: 0.0
  precision: 0.16666666666666666
  recall: 0.6666666666666666
  roc_auc: 0.0
  tn: 1
  tp: 2
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SZIkSZIk6T8=
  epoch: 1
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.07924610748887062
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 11
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SZIkSZIk6T8=
  epoch: 2
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.06534746987745166
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 11
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SZIkSZIk6T8=
  epoch: 3
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.04033762635663152
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 11
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SZIkSZIk6T8=
  epoch: 4
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.05237918393686414
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 11
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SZIkSZIk6T8=
  epoch: 5
  f1: 0.0
  fn: 3
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.038498415844514966
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 11
  tp: 0
val_metrics:
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 0
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.11418423056602478
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 1
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.04583744704723358
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 2
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.01265683677047491
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 3
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.010467611253261566
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 4
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.011270995251834393
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
- accuracy: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8D8=
  epoch: 5
  f1: 0.0
  fn: 0
  fp: 0
  fraud_f1: 0.0
  fraud_precision: 0.0
  fraud_recall: 0.0
  loss: 0.02006402052938938
  pr_auc: 0.0
  precision: 0.0
  recall: 0.0
  roc_auc: 0.0
  tn: 3
  tp: 0
